---
title: "Data Processing"
output: html_document
---


### library and read files
```{r}
library(dplyr)
library(ggplot2)
library(tidyr)

posts_df <- read.csv("./data/movies_may_2015_posts.csv", stringsAsFactors = FALSE)
gbo_df <- read.csv("./data/movies_may_2015_gbo.csv", stringsAsFactors = FALSE)

```

### data clean up 
```{r}

#fix date
posts_df <- posts_df %>%
  mutate(date_post = as.Date(created_date, "%Y-%m-%d"))

gbo_df <- gbo_df %>%
  mutate(gbo_date = as.Date(date, "%m/%d/%y"),
         release_date = as.Date(release_date, "%m/%d/%y"))
  

```


## join data sources
```{r}
# outer join posts and gbo on movie name and date.  each row => movie_name, date, gbo on that day, number of posts on that day
gbo_post_df <- posts_df %>% 
  group_by(movie_name, date_post) %>% 
  count() %>% #count number of posts per movie on date
  ungroup() %>%
  full_join(select(gbo_df, gbo_date, movie_name, Daily), by = c("movie_name" = "movie_name", "date_post" = "gbo_date"))
names(gbo_post_df) <- c("movie_name", "date", "num_posts", "Daily")

# covert gbo from char to num
gbo_post_df <- gbo_post_df %>% mutate(gbo_daily = as.numeric(gsub("[$,]","",Daily)))
gbo_post_df <- select(gbo_post_df, -Daily)

# calculate days from / to release date, and log values
gbo_post_df <- inner_join(gbo_post_df, select(gbo_df, movie_name, release_date) %>% distinct(), by = c("movie_name")) %>%
  mutate(daysFromToRelease = date - release_date) %>%
  mutate(daysFromToRelease = as.integer(daysFromToRelease),
         log_gbo_daily = log(gbo_daily),
         log_num_posts = log(num_posts+1))
  
# pivot long
gbo_post_df_long <- pivot_longer(gbo_post_df, cols = c("num_posts","gbo_daily","log_num_posts","log_gbo_daily"), names_to = "series")

```
