---
title: "movies_may2015"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
```

## read files
```{r}
posts_df <- read.csv("movies_may_2015_posts.csv", stringsAsFactors = FALSE)
gbo_df <- read.csv("movies_may_2015_gbo.csv", stringsAsFactors = FALSE)

```

## data clean up
```{r}

posts_df <- posts_df %>%
  mutate(date_post = as.Date(created_date, "%Y-%m-%d"))

gbo_df <- gbo_df %>%
  mutate(gbo_date = as.Date(date, "%m/%d/%y"),
         release_date = as.Date(release_date, "%m/%d/%y"))
  

```


## join 
```{r}

gbo_post_df <- posts_df %>% 
  group_by(movie_name, date_post) %>% 
  count() %>%
  ungroup() %>%
  full_join(select(gbo_df, gbo_date, movie_name, Daily), by = c("movie_name" = "movie_name", "date_post" = "gbo_date"))
names(gbo_post_df) <- c("movie_name", "date", "num_posts", "Daily")

gbo_post_df <- gbo_post_df %>% mutate(gbo_daily = as.numeric(gsub("[$,]","",Daily)))
gbo_post_df <- select(gbo_post_df, -Daily)

gbo_post_df <- inner_join(gbo_post_df, select(gbo_df, movie_name, release_date) %>% distinct(), by = c("movie_name")) %>%
  mutate(daysFromToRelease = date - release_date) %>%
  mutate(daysFromToRelease = as.integer(daysFromToRelease),
         log_gbo_daily = log(gbo_daily),
         log_num_posts = log(num_posts+1))
  

gbo_post_df_no_na <- na.omit(gbo_post_df) 

gbo_post_df_na_zero <- gbo_post_df %>% mutate(gbo_daily = ifelse(is.na(gbo_daily), 0, gbo_daily),
                       num_posts = ifelse(is.na(num_posts), 0, num_posts)) 

gbo_post_df_na_zero_long <- pivot_longer(gbo_post_df_na_zero, cols = c("num_posts","gbo_daily","log_num_posts","log_gbo_daily"), names_to = "series")
gbo_post_df_no_na_long <- pivot_longer(gbo_post_df_no_na, cols = c("num_posts","gbo_daily","log_num_posts","log_gbo_daily"), names_to = "series")
gbo_post_df_long <- pivot_longer(gbo_post_df, cols = c("num_posts","gbo_daily","log_num_posts","log_gbo_daily"), names_to = "series")



```

## gbo after release 
```{r}

gbo_post_df_long %>%
  filter(release_date >= "2015-05-01") %>%
  filter(series == "log_gbo_daily" & daysFromToRelease <=100) %>%
  #mutate(value = ifelse(series == "gbo_daily", value*10^-6, value)) %>%
  ggplot(aes(x = daysFromToRelease, y = value)) +
  geom_point() +
  #guides(color = FALSE, size = FALSE)
  geom_smooth() + 
  theme_bw() +
  labs(title = "Decline in Daily GBO after release date", x = "Days After Release", y = "Log Daily GBO") +
  geom_vline(xintercept = 0, linetype="dotted", 
                color = "red", size=0.5) +
  scale_x_continuous(limits = c(0,100))
  

```

## postm before after release 
```{r}

gbo_post_df_long %>%
  filter(release_date >= "2015-05-01") %>%
  filter(series == "log_num_posts" & daysFromToRelease <=100) %>%
  ggplot(aes(x = daysFromToRelease, y = value)) +
  geom_point() +
  geom_smooth() +
  geom_vline(xintercept = 0, linetype="dotted", 
                color = "red", size=0.5) +
  theme_bw() +
  labs(title = "Number of Reddit Posts before and after release date", x = "Days Before/After Release (day 0 is release date)", y = "Log Number Posts") 
  

  

```

## do more posts have an impact on how gbo declines
```{r}
# bin movies on num posts
total_movie_posts <- gbo_post_df_long %>%
  filter(release_date >= "2015-05-01") %>%
  filter(series == "num_posts" & daysFromToRelease <=100) %>%
  group_by(movie_name) %>% 
  summarise(sum_posts = sum(value, na.rm = TRUE))


total_movie_posts$posts_bin <- ifelse(total_movie_posts$sum_posts > 100, ">100 posts",
                                     ifelse(total_movie_posts$sum_posts >= 1, "1-100 posts", "0 posts"))



# visualize
gbo_post_df_long %>%
  filter(release_date >= "2015-05-01") %>%
  filter(series == "log_gbo_daily" & daysFromToRelease <=100) %>%
  inner_join(total_movie_posts, by = c("movie_name")) %>%
  ggplot(aes(x = daysFromToRelease, y = value, col = posts_bin)) +
  geom_point() +
  #guides(color = FALSE, size = FALSE)
  geom_smooth() + 
  theme_bw() +
  labs(title = "Decline in GBO after release date (binned by number of posts)", x = "Days After Release", y = "Log GBO") +
  geom_vline(xintercept = 0, linetype="dotted", 
                color = "red", size=0.5) +
  scale_x_continuous(limits = c(0,100))
  
  
```

## stats test
```{r}

reg_data <- gbo_post_df %>%
  filter(release_date >= "2015-05-01") %>%
  filter(daysFromToRelease <=100) %>%
  inner_join(total_movie_posts, by = c("movie_name")) %>%
  select(movie_name, daysFromToRelease, log_gbo_daily, posts_bin) %>%
  na.omit()

reg_data %>%
   group_by(posts_bin) %>% distinct(movie_name) %>% count()

summary(lm(log_gbo_daily ~ daysFromToRelease*posts_bin, data = reg_data))

```

## rolling gbo and posts, as posts increase does gbo increase
```{r}

gbo_post_df_na_zero_cumsum <- gbo_post_df_na_zero %>%
  arrange(movie_name, date) %>%
  group_by(movie_name) %>%
  mutate(gbo_daily_sum = cumsum(gbo_daily),
         num_posts_sum = cumsum(num_posts)) %>%
  ungroup() %>%
  mutate(daysFromToRelease = as.integer(daysFromToRelease),
         log_gbo_daily_sum = log(gbo_daily_sum+1),
         log_num_posts_sum = log(num_posts_sum+1))

  
gbo_post_df_na_zero_cumsum %>%
  filter(release_date >= "2015-05-01" & log_gbo_daily_sum > 0) %>%
  ggplot(aes(x = log_num_posts_sum, y = log_gbo_daily_sum)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_bw() +
  labs(title = "Positive association of increasing GBO as Number of Posts increase", x = "Log Number of Posts", y = "Log Daily GBO")


#num of movies: 34
gbo_post_df_na_zero_cumsum %>%
  filter(release_date >= "2015-05-01"  & log_gbo_daily_sum > 0) %>% distinct(movie_name)
```
## stats
```{r}
reg_data2 <- gbo_post_df_na_zero_cumsum %>%
  filter(release_date >= "2015-05-01" & log_gbo_daily_sum > 0)
summary(lm(log_gbo_daily_sum ~ log_num_posts_sum, data = reg_data2))

```

## avengers

```{r}
release_list <- select(filter(gbo_df, grepl("Avengers",movie_name)),release_date)

gbo_post_df_no_na_long %>%
  mutate(value = ifelse(series == "gbo_daily", value*10^-6, value)) %>%
  filter(grepl("Avengers",movie_name)) %>%
  ggplot(aes(x = date, y = value, col = series, shape = series)) +
  geom_point() +
  geom_vline(xintercept = as.Date("2015-05-01","%Y-%m-%d"), linetype="dotted", 
                color = "blue", size=1.5)
  


```











